# -*- coding: utf-8 -*-
"""Pmusic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wwAUhBGoNj0v_LT8_E8giLxN6gmdmBB_
"""

from google.colab import drive

drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd ./drive/MyDrive

!python -m pip install -U yt-dlp

from yt_dlp import YoutubeDL

ydl_opts = {'format': 'best'}

with YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://www.youtube.com/watch?v=M2cckDmNLMI'])

!yt-dlp -f best -v https://youtu.be/M2cckDmNLMI' -o Pmusic.mp4

!yt-dlp -x --audio-format mp3 https://youtu.be/M2cckDmNLMI'

!yt-dlp -x --audio-format mp3 https://youtu.be/M2cckDmNLMI -o Pmusic.mp3

!apt install ffmpeg

pip install spleeter

from IPython.display import Audio

Audio('Pmusic.mp3')

!spleeter separate -h

!spleeter separate -o output/ Pmusic.mp3

!ls output/Pmusic

Audio('output/Pmusic/vocals.wav')

Audio('output/Pmusic/accompaniment.wav')